### PR TITLE
Fix backlight not being turned on

### LINKED ISSUE #119: The background light on Yeelight Screen Bar Pro does not turn on
Hi there, all
After setting up the plugin and connecting my lamp to Homekit, I encountered the problem that all functions work fine without any complaints. However, if I turn off the background light by the Homekit and try to turn it back on, nothing happens.

To turn on it I need to change the brightness in Homekit and then the light turns on.

When its happing I don't see any errors in Homebridge logs

### PR DESCRIPTION
**Pull request by bimusiek**
I have checked and even Yeelight app which sends "bg_toggle" command does not properly works. Only thing that makes the backlight work is to send command 
```
{"method":"bg_set_scene","params":["color",9055202,-1]}
```
from the Yeelight app (by tapping on any color).
Based on this, I assume we have to send `-1` as PowerMode, thus the PR with a change.
I have 2 lights recently bought and I validated it works now with both of those.

This fixes https://github.com/cellcortex/homebridge-yeelighter/issues/119

### CODE REVIEW

**Comment by bimusiek** [comment]
After more testing, it did not work. I have to use `bg_set_scene` to turn it on. Yeelight app has the same problem where you have to use the scene. I have the newest firmware available and this is the only workaround.

**Review by cellcortex — CHANGES_REQUESTED** [review]
Unfortunately I cannot accept it this way. 
* package.json should not be changing in the PR
* this behaviour change would need to be made optional. 
* I don't understand the value of saving the lastHue and lastSat but never reading it

**Comment by bimusiek** [comment]
I can make the behavior configurable. About the values, those are used in setHSV method afaik.

**Comment by bimusiek** [comment]
@cellcortex Finally got to it, the changes you requested are implemented.

**Comment by bimusiek** [comment]
@cellcortex Any thoughts?

**Review by cellcortex — APPROVED** [review]

**Pull request merged**
